AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  schedule-lead-callback-service

  A microservice that adds a lead to the Firestore callback queue, invoked by a webhook.

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: nodejs18.x

Resources:
  ScheduleLeadCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Description: Adds a lead to the callback queue.
      CodeUri: ./
      Policies:
        - VPCAccessPolicy: {}
        # Grant permission to read and decrypt the Firebase Service Account from SSM
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource: !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/firebase-service-account'
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource: !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm'
      Environment:
        Variables:
          FIREBASE_SERVICE_ACCOUNT: '/app/firebase-service-account'

Outputs:
  ScheduleLeadCallbackFunctionName:
    Description: "The name of the Schedule Lead Callback Lambda function"
    Value: !Ref ScheduleLeadCallbackFunction